name: teste
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:

  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_charts: ^20.3.59
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_speed_dial: ^6.2.0
  math_expressions: ^1.1.1

  # image carousel slider
  carousel_slider: ^4.1.1

  # dots indicator
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logotipo.png
    - assets/images/background/
    - assets/images/option_icons/
    - assets/images/credit_cards/
    - assets/images/credit_cards_flags/
    - assets/images/bank_accounts/
    - assets/images/login_icons/facebook.png
    - assets/images/login_icons/google.png
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-Medium.ttf
          weight: 500
