// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuuPPJt1yN1LUNRgt89OMVg0PLaDyrcu8',
    appId: '1:621463436077:web:9451288f440740700fb1a4',
    messagingSenderId: '621463436077',
    projectId: 'pit01gp07-c4ff3',
    authDomain: 'pit01gp07-c4ff3.firebaseapp.com',
    storageBucket: 'pit01gp07-c4ff3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq7xmakepvjkrFC2fnTw4mFkLApmbEoKs',
    appId: '1:621463436077:android:2446229d60a2a10d0fb1a4',
    messagingSenderId: '621463436077',
    projectId: 'pit01gp07-c4ff3',
    storageBucket: 'pit01gp07-c4ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsVOeXZA0QuRlyKIpOMCJuQb9BcmnWDqw',
    appId: '1:621463436077:ios:e04c0168c01e0f010fb1a4',
    messagingSenderId: '621463436077',
    projectId: 'pit01gp07-c4ff3',
    storageBucket: 'pit01gp07-c4ff3.appspot.com',
    iosClientId: '621463436077-a1nf6f0nj2ddrj05qd5tr5pnbca51agv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pit01gp07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsVOeXZA0QuRlyKIpOMCJuQb9BcmnWDqw',
    appId: '1:621463436077:ios:e04c0168c01e0f010fb1a4',
    messagingSenderId: '621463436077',
    projectId: 'pit01gp07-c4ff3',
    storageBucket: 'pit01gp07-c4ff3.appspot.com',
    iosClientId: '621463436077-a1nf6f0nj2ddrj05qd5tr5pnbca51agv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pit01gp07',
  );
}
